-- Generated by DataForge from DataHub metadata
-- Request: "Check data freshness for all tier-1 datasets"
-- Source tables: raw.stripe.payments, raw.shopify.orders, raw.stripe.customers

with freshness_checks as (

    select
        'raw.stripe.payments' as dataset_name,
        'tier-1' as tier,
        max(created_at) as latest_record,
        current_timestamp() as checked_at,
        datediff('hour', max(created_at), current_timestamp()) as hours_stale,
        count(*) as total_rows,
        count(*) - count(payment_id) as null_key_count
    from raw.stripe.payments

    union all

    select
        'raw.shopify.orders' as dataset_name,
        'tier-1' as tier,
        max(order_date) as latest_record,
        current_timestamp() as checked_at,
        datediff('hour', max(order_date), current_timestamp()) as hours_stale,
        count(*) as total_rows,
        count(*) - count(order_id) as null_key_count
    from raw.shopify.orders

    union all

    select
        'raw.stripe.customers' as dataset_name,
        'tier-1' as tier,
        max(created_at) as latest_record,
        current_timestamp() as checked_at,
        datediff('hour', max(created_at), current_timestamp()) as hours_stale,
        count(*) as total_rows,
        count(*) - count(customer_id) as null_key_count
    from raw.stripe.customers

)

select
    dataset_name,
    tier,
    latest_record,
    hours_stale,
    case
        when hours_stale <= 1 then 'FRESH'
        when hours_stale <= 24 then 'OK'
        when hours_stale <= 72 then 'STALE'
        else 'CRITICAL'
    end as freshness_status,
    total_rows,
    null_key_count,
    round(null_key_count * 100.0 / nullif(total_rows, 0), 2) as null_key_pct,
    checked_at
from freshness_checks
order by hours_stale desc
