-- Generated by DataForge from DataHub metadata
-- Source tables: raw.stripe.payments, raw.shopify.orders, raw.shopify.products
-- Grounded in: 28 verified columns across 3 datasets

{{
    config(
        materialized='table',
        tags=['mart', 'revenue', 'finance']
    )
}}

with payments as (

    select
        payment_id,
        customer_id,
        amount / 100.0 as amount_usd,  -- amount stored in cents
        currency,
        status,
        created_at as payment_date
    from {{ source('stripe', 'payments') }}
    where status = 'succeeded'

),

orders as (

    select
        order_id,
        total_price,
        subtotal_price,
        currency,
        financial_status,
        order_date,
        line_items_json
    from {{ source('shopify', 'orders') }}
    where financial_status = 'paid'

),

order_items as (

    select
        o.order_id,
        o.order_date,
        o.total_price,
        f.value:product_id::varchar(64) as product_id,
        f.value:quantity::integer as quantity,
        f.value:price::number(12,2) as line_price
    from orders o,
    lateral flatten(input => o.line_items_json) f

),

products as (

    select
        product_id,
        title as product_title,
        coalesce(product_type, 'Uncategorized') as product_category,
        vendor
    from {{ source('shopify', 'products') }}

),

revenue_by_item as (

    select
        date_trunc('month', oi.order_date)::date as revenue_month,
        p.product_category,
        p.vendor,
        count(distinct oi.order_id) as order_count,
        sum(oi.quantity) as units_sold,
        sum(oi.line_price * oi.quantity) as gross_revenue
    from order_items oi
    inner join products p
        on oi.product_id = p.product_id
    group by 1, 2, 3

),

refunds as (

    select
        date_trunc('month', created_at)::date as refund_month,
        sum(amount / 100.0) as refund_amount
    from {{ source('stripe', 'payments') }}
    where status = 'refunded'
    group by 1

)

select
    r.revenue_month,
    r.product_category,
    r.vendor,
    r.order_count,
    r.units_sold,
    r.gross_revenue,
    coalesce(ref.refund_amount, 0) as refunds,
    r.gross_revenue - coalesce(ref.refund_amount, 0) as net_revenue
from revenue_by_item r
left join refunds ref
    on r.revenue_month = ref.refund_month
order by r.revenue_month desc, r.gross_revenue desc
