-- Generated by DataForge from DataHub metadata
-- Source tables: raw.stripe.payments, raw.stripe.customers, raw.shopify.orders
-- PII handling: customer email masked, only aggregates exposed

{{
    config(
        materialized='table',
        tags=['mart', 'customer', 'segmentation']
    )
}}

with customer_orders as (

    select
        o.customer_email,
        md5(o.customer_email) as customer_hash,  -- mask PII
        count(distinct o.order_id) as total_orders,
        sum(o.total_price) as total_spend,
        min(o.order_date) as first_order_date,
        max(o.order_date) as last_order_date,
        datediff('day', min(o.order_date), max(o.order_date)) as customer_tenure_days
    from {{ source('shopify', 'orders') }} o
    where o.financial_status = 'paid'
    group by 1, 2

),

customer_payments as (

    select
        c.customer_id,
        c.created_at as account_created_at,
        count(distinct p.payment_id) as payment_count,
        sum(case when p.status = 'succeeded' then p.amount / 100.0 else 0 end) as total_paid,
        sum(case when p.status = 'refunded' then p.amount / 100.0 else 0 end) as total_refunded,
        avg(case when p.status = 'succeeded' then p.amount / 100.0 end) as avg_payment_amount
    from {{ source('stripe', 'customers') }} c
    left join {{ source('stripe', 'payments') }} p
        on c.customer_id = p.customer_id
    group by 1, 2

),

segmented as (

    select
        co.customer_hash,
        co.total_orders,
        co.total_spend,
        co.first_order_date,
        co.last_order_date,
        co.customer_tenure_days,
        cp.payment_count,
        cp.total_paid,
        cp.total_refunded,
        cp.avg_payment_amount,
        case
            when co.total_spend >= 500 and co.total_orders >= 5 then 'VIP'
            when co.total_spend >= 200 or co.total_orders >= 3 then 'Regular'
            when co.total_orders = 1 then 'One-time'
            else 'Inactive'
        end as customer_segment,
        case
            when datediff('day', co.last_order_date, current_date()) <= 30 then 'Active'
            when datediff('day', co.last_order_date, current_date()) <= 90 then 'At Risk'
            else 'Churned'
        end as activity_status,
        coalesce(cp.total_refunded / nullif(cp.total_paid, 0), 0) as refund_rate
    from customer_orders co
    left join customer_payments cp
        on md5(cp.customer_id) = co.customer_hash

)

select * from segmented
